version: '3' 

volumes: 
  pg_data: 

services: 
  db:
    container_name: random_coffe_bot
    image: sstc/sqlite3:latest 
    env_file: .env 
    volumes: 
      - pg_data:/var/lib/sqlite3/data

  backend:
    container_name: random_coffe_bot_backend 
    build: ./
    env_file: .env 
    depends_on: 
      - db