"""meetings is deleted

Revision ID: 0e06a16123e5
Revises: 2ab1783cc0a5
Create Date: 2024-03-20 08:53:03.119383

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0e06a16123e5'
down_revision: Union[str, None] = '2ab1783cc0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('user_1', sa.INTEGER(), nullable=False),
    sa.Column('user_2', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('user_1 != user_2'),
    sa.ForeignKeyConstraint(['user_1'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_2'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_1')
    )
    # ### end Alembic commands ###
