"""is_sent added to User

Revision ID: 2ab1783cc0a5
Revises: 3b5294c253ea
Create Date: 2024-03-20 08:10:13.979822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab1783cc0a5'
down_revision: Union[str, None] = '3b5294c253ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_sent')
    # ### end Alembic commands ###
