"""Add user relationship to Reservation

Revision ID: 967c0f4867ab
Revises: b0d0a90b8626
Create Date: 2024-01-26 11:00:17.245842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967c0f4867ab'
down_revision = 'b0d0a90b8626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reservation_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reservation_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
